branches: main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - prepareCmd: 'task prepare VERSION=${nextRelease.version}'
      publishCmd: 'task publish VERSION=${nextRelease.version}'
      successCmd: 'task success VERSION=${nextRelease.version}'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: '# Semantic Versioning Changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - Taskfile.yaml
        - charts/portfolio-operator/Chart.yaml
  - - '@semantic-release/github'
    - assets:
        - path: release/**