version: '3'
env:
  VERSION: 0.1.0
includes:
  charts:
    taskfile: ./charts
    dir: ./charts
tasks:
  default:
    cmds:
      - task -l
    silent: true
  dev-install:
    desc: Install Dev Dependencies
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@v1.16.4
      - go install github.com/google/ko@v0.17.1
  coverage:
    desc: Generate Code Coverage Report
    sources:
      - '**/*.go'
    cmds:
      - mkdir -p build/coverage
      - go test -cover -covermode=count -shuffle=on -timeout 2s -coverprofile=build/coverage/coverage.out ./...
      - go tool cover -html=build/coverage/coverage.out -o build/coverage/index.html
      - echo "Coverage Generated"
  format:
    desc: Format golang
    sources:
      - '**/*.go'
    cmds:
      - go fmt ./...
  swagger-generation:
    sources:
      - '**/*.go'
    desc: Generate swagger docs
    cmds:
      - swag init --parseDependency -g internal/api/main.go
  run:
    desc: Run Program
    cmds:
      - go run cmd/server/main.go
  test:
    desc: Execute unit tests.
    deps:
      - coverage
  release-helm:
    cmds:
      - mkdir -p release
      - yq e '.appVersion |= "{{.VERSION}}"' -i charts/portfolio-operator/Chart.yaml
      - helm package --app-version {{.VERSION}} charts/portfolio-operator
      - mv *.tgz release
      - echo "{{.GITHUB_TOKEN}}" | helm registry login -u doesntmatter --password-stdin ghcr.io/criyl
      - helm push release/portfolio-operator-{{.VERSION}}.tgz oci://ghcr.io/criyl
  release-controller-image:
    desc: Build KO Image
    env:
      KO_DOCKER_REPO: ghcr.io/criyl/portfolio-operator-controller
      GITHUB_TOKEN: ""
    cmds:
      - echo "{{.GITHUB_TOKEN}}" | ko login ghcr.io --username doesntmatter --password-stdin
      - |
        ko build --bare \
        -t {{.VERSION}} \
        --image-label org.opencontainers.image.source=https://github.com/criyl/portfolio-operator \
        ./cmd/server
  prepare:
    desc: Trigger new Release
    cmds:
      - yq e '.env.VERSION |= "{{.VERSION}}"' -i Taskfile.yaml
      - task: prepare-controller-image
      - task: charts:prepare-helm
  publish:
    desc: Trigger new Release
    cmds:
      - task: release-controller-image
      - task: charts:release-helm
  success:
    cmds:
      - echo stub for success hook
  release:
    desc: Trigger new Release
    cmds:
      - yq e '.env.VERSION |= "{{.VERSION}}"' -i Taskfile.yaml
      - task: release-controller-image
      - task: charts:release-helm
